# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dotagents < Formula
  desc "Sync skills, MCP servers, hooks, and roles across coding agents"
  homepage "https://github.com/yourconscience/dotagents"
  version "0.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yourconscience/dotagents/releases/download/v0.8.0/dotagents_0.8.0_darwin_amd64.tar.gz"
      sha256 "099d93ce539727a2da8b068b8de97f8481309de354ec65d45b2925fcf806e2b2"

      define_method(:install) do
        bin.install "dotagents"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yourconscience/dotagents/releases/download/v0.8.0/dotagents_0.8.0_darwin_arm64.tar.gz"
      sha256 "9a19900888f5f35f3f004d040ce463007ccc02e32d8c1c9fe7d98362e5ae522c"

      define_method(:install) do
        bin.install "dotagents"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yourconscience/dotagents/releases/download/v0.8.0/dotagents_0.8.0_linux_amd64.tar.gz"
      sha256 "e6b18712f9649ce6abffb69f0234ed10ef208034829a941da8ea8358fc69f8b4"
      define_method(:install) do
        bin.install "dotagents"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yourconscience/dotagents/releases/download/v0.8.0/dotagents_0.8.0_linux_arm64.tar.gz"
      sha256 "a59e3e22e6dc4857b55d8462b217d791d389a22f694b6d5aaa5567b141e878c3"
      define_method(:install) do
        bin.install "dotagents"
      end
    end
  end
end
