# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dotagents < Formula
  desc "Sync skills, MCP servers, hooks, and roles across coding agents"
  homepage "https://github.com/yourconscience/dotagents"
  version "0.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yourconscience/dotagents/releases/download/v0.7.0/dotagents_0.7.0_darwin_amd64.tar.gz"
      sha256 "d6f56c02781df178f386b0cab48fc26e26133cda57e15b8576ddfa80c2cff99e"

      define_method(:install) do
        bin.install "dotagents"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yourconscience/dotagents/releases/download/v0.7.0/dotagents_0.7.0_darwin_arm64.tar.gz"
      sha256 "47389ddf17c7ff37626df544fd9bdda54ba0e603b984426c82118146d871303f"

      define_method(:install) do
        bin.install "dotagents"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yourconscience/dotagents/releases/download/v0.7.0/dotagents_0.7.0_linux_amd64.tar.gz"
      sha256 "9d90f37c7d8f37d447710c053988c50d14c41c1e3868bf2c39c262617fc72a64"
      define_method(:install) do
        bin.install "dotagents"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yourconscience/dotagents/releases/download/v0.7.0/dotagents_0.7.0_linux_arm64.tar.gz"
      sha256 "079318bccfd641443a827566621b0b499c6aa92dca86edd92bc92c409bf21cce"
      define_method(:install) do
        bin.install "dotagents"
      end
    end
  end
end
