# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tackroom < Formula
  desc "Sync skills, MCP servers, hooks, and roles across coding agents"
  homepage "https://github.com/yourconscience/tackroom"
  version "1.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yourconscience/tackroom/releases/download/v1.3.0/tackroom_1.3.0_darwin_amd64.tar.gz"
      sha256 "1f362a2f82fab0d6ae708ccfda4432789262bd37e1f7c92d600d16566d432577"

      define_method(:install) do
        bin.install "tackroom"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yourconscience/tackroom/releases/download/v1.3.0/tackroom_1.3.0_darwin_arm64.tar.gz"
      sha256 "0a4649e0ff60f9b35e5e9a4646a0ee20e473706ee65b1c8ca67037e312de322e"

      define_method(:install) do
        bin.install "tackroom"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yourconscience/tackroom/releases/download/v1.3.0/tackroom_1.3.0_linux_amd64.tar.gz"
      sha256 "fb8261513ad11e84c21539f4fa4c3eb5e7ef924bdd0f7609b7696ba464414e9d"
      define_method(:install) do
        bin.install "tackroom"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yourconscience/tackroom/releases/download/v1.3.0/tackroom_1.3.0_linux_arm64.tar.gz"
      sha256 "ecc61d7b726f99fb11b5db1859a85dfe66eb35db8fde09aa3563532d816039a0"
      define_method(:install) do
        bin.install "tackroom"
      end
    end
  end
end
