# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tackroom < Formula
  desc "Sync skills, MCP servers, hooks, and roles across coding agents"
  homepage "https://github.com/yourconscience/tackroom"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yourconscience/tackroom/releases/download/v1.2.0/tackroom_1.2.0_darwin_amd64.tar.gz"
      sha256 "a9cf047296a04faa8ca5d07b406226370ec2c91bbbb82bb235d34d4efe4a982c"

      define_method(:install) do
        bin.install "tackroom"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yourconscience/tackroom/releases/download/v1.2.0/tackroom_1.2.0_darwin_arm64.tar.gz"
      sha256 "ce190a9fbdea7e07f1e9dff6688701ec710299f4f5d122bd316b23657bb86b0d"

      define_method(:install) do
        bin.install "tackroom"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yourconscience/tackroom/releases/download/v1.2.0/tackroom_1.2.0_linux_amd64.tar.gz"
      sha256 "eaa0ea412872da501f57d63b69bbf38e12c35204f24f11cfa3ba22356758ea02"
      define_method(:install) do
        bin.install "tackroom"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yourconscience/tackroom/releases/download/v1.2.0/tackroom_1.2.0_linux_arm64.tar.gz"
      sha256 "29b85ea5c0971e888474b996fb06e74423fd2224ddc9d87f4f491bf79f5c8726"
      define_method(:install) do
        bin.install "tackroom"
      end
    end
  end
end
