# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tackroom < Formula
  desc "Sync skills, MCP servers, hooks, and roles across coding agents"
  homepage "https://github.com/yourconscience/tackroom"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yourconscience/tackroom/releases/download/v1.0.1/tackroom_1.0.1_darwin_amd64.tar.gz"
      sha256 "069dfb8be4cee0736f7830f7681647e4e67f117d38b1fd0a5e3f9e4b20f6411e"

      define_method(:install) do
        bin.install "tackroom"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yourconscience/tackroom/releases/download/v1.0.1/tackroom_1.0.1_darwin_arm64.tar.gz"
      sha256 "64b7a153cb1bcd37ed27e047638976a43e844aeb17445e5d15bb3e73a4750fd3"

      define_method(:install) do
        bin.install "tackroom"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yourconscience/tackroom/releases/download/v1.0.1/tackroom_1.0.1_linux_amd64.tar.gz"
      sha256 "4526c596b7715408b8d5e55cb4c45a8a4aea7f9d6ce6a4d7c0bd468d2498341c"
      define_method(:install) do
        bin.install "tackroom"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yourconscience/tackroom/releases/download/v1.0.1/tackroom_1.0.1_linux_arm64.tar.gz"
      sha256 "ec38a945f56feff20510dbcf79ab13c0b2c03e67df73aad8b0ca8fb7b64074f6"
      define_method(:install) do
        bin.install "tackroom"
      end
    end
  end
end
